### ISSUE TITLE
image/photo upload

### ISSUE THREAD

**Issue by simonneutert** [simonneutert/labradorite-notebook#1]
#### Todos

- [x] store attachments next to `memos.[yaml|md]`
- [x] in overview as thumbs next to tags, click copies link, user can insert either `<img src="...">` or markdown tags for media
- [x] delete from disk on delete
